"""hack

Revision ID: 681d93c9fb50
Revises: e90fce6e8d87
Create Date: 2016-05-12 10:35:03.246063

"""

# revision identifiers, used by Alembic.
revision = '681d93c9fb50'
down_revision = 'e90fce6e8d87'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'tweet_ibfk_1', 'tweet', type_='foreignkey')
    op.drop_column('tweet', 'user_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet', sa.Column('user_id', mysql.VARCHAR(collation=u'utf8mb4_unicode_ci', length=50), nullable=True))
    op.create_foreign_key(u'tweet_ibfk_1', 'tweet', 'user', ['user_id'], ['user_id'])
    ### end Alembic commands ###
