"""max/min sentiment word/values on Tweet objects

Revision ID: 846b309891a8
Revises: be4d7f6ea411
Create Date: 2016-05-12 06:30:23.830245

"""

# revision identifiers, used by Alembic.
revision = '846b309891a8'
down_revision = 'be4d7f6ea411'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet', sa.Column('max_sentiment_word_value', sa.String(length=150), nullable=True))
    op.add_column('tweet', sa.Column('min_sentiment_word_value', sa.String(length=150), nullable=True))
    op.alter_column('user', 'country_code',
               existing_type=mysql.VARCHAR(collation=u'utf8mb4_unicode_ci', length=10),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'country_code',
               existing_type=mysql.VARCHAR(collation=u'utf8mb4_unicode_ci', length=10),
               nullable=False)
    op.drop_column('tweet', 'min_sentiment_word_value')
    op.drop_column('tweet', 'max_sentiment_word_value')
    ### end Alembic commands ###
