"""text column on Tweet table; removal of url from same

Revision ID: 9cd5befa5647
Revises: f7626c1aac6d
Create Date: 2016-03-22 03:04:41.330611

"""

# revision identifiers, used by Alembic.
revision = '9cd5befa5647'
down_revision = 'f7626c1aac6d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet', sa.Column('text', sa.String(length=150), nullable=False))
    op.drop_index('url', table_name='tweet')
    op.drop_column('tweet', 'url')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet', sa.Column('url', mysql.VARCHAR(collation=u'utf8mb4_unicode_ci', length=100), nullable=False))
    op.create_index('url', 'tweet', ['url'], unique=True)
    op.drop_column('tweet', 'text')
    ### end Alembic commands ###
