"""user tweets relationship

Revision ID: af3b896e5bff
Revises: 0bfcf877ea3a
Create Date: 2016-05-13 20:38:31.025857

"""

# revision identifiers, used by Alembic.
revision = 'af3b896e5bff'
down_revision = '0bfcf877ea3a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tweet_user_id', table_name='tweet')
    op.create_foreign_key(None, 'tweet', 'user', ['user_id'], ['user_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tweet', type_='foreignkey')
    op.create_index('ix_tweet_user_id', 'tweet', ['user_id'], unique=False)
    ### end Alembic commands ###
