"""sentiment column on tweet table

Revision ID: be4d7f6ea411
Revises: f356dc5ee0e3
Create Date: 2016-05-12 05:47:20.226567

"""

# revision identifiers, used by Alembic.
revision = 'be4d7f6ea411'
down_revision = 'f356dc5ee0e3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet', sa.Column('sentiment', sa.String(length=10), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweet', 'sentiment')
    ### end Alembic commands ###
