"""biginteger

Revision ID: e90fce6e8d87
Revises: 846b309891a8
Create Date: 2016-05-12 08:24:15.783513

"""

# revision identifiers, used by Alembic.
revision = 'e90fce6e8d87'
down_revision = '846b309891a8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
