"""user addition and small tweaks accordingly

Revision ID: f356dc5ee0e3
Revises: f857527a8ebe
Create Date: 2016-05-12 00:29:17.197284

"""

# revision identifiers, used by Alembic.
revision = 'f356dc5ee0e3'
down_revision = 'f857527a8ebe'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_sentiment_topic'), 'sentiment', ['topic'], unique=False)
    op.drop_index('ix_tweet_user_id', table_name='tweet')
    op.create_foreign_key(None, 'tweet', 'user', ['user_id'], ['user_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tweet', type_='foreignkey')
    op.create_index('ix_tweet_user_id', 'tweet', ['user_id'], unique=False)
    op.drop_index(op.f('ix_sentiment_topic'), table_name='sentiment')
    op.drop_table('user')
    ### end Alembic commands ###
