"""initialization

Revision ID: f7626c1aac6d
Revises:
Create Date: 2016-03-21 19:43:39.437546

"""

# revision identifiers, used by Alembic.
revision = 'f7626c1aac6d'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweet',
    sa.Column('tweet_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('user_screen_name', sa.String(length=100), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('tweet_id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_tweet_user_id'), 'tweet', ['user_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tweet_user_id'), table_name='tweet')
    op.drop_table('tweet')
    ### end Alembic commands ###
